'use strict';

/* Controllers */

var sandalyControllers = angular.module('sandalyControllers', []);


sandalyControllers.controller('FilterCtrl', [ '$scope', '$http',
                                        		function($scope, $http) {
	

	
}]);

sandalyControllers.controller('ShoeListCtrl', [ '$scope', '$http',
		function($scope, $http) {
	
	$scope.showCollection = false;
	$scope.showColor = false;
	$scope.showPrice = false;
	$scope.colorFilter = "";
	
			$scope.shoes = [
			                {
    "brand": "BORN",
    "condition": "New",
    "description": "The subtlety of leather in rich color combinations gives this comfort style a fresh twist.   Full-grain leather   Leather lining  Polyurethane outsole  Steel shank  Opanka hand-crafted construction  Heel height: 2 1/4 inches",
    "id": 2793,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/born/Pair/B89626-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=2793&refURL=gcs",
    "price": 71.7,
    "product_type": "Sandals",
    "title": "Born Women's Shoes - Hanita in Whiskey",
    "color": "Whiskey",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 594,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 360059,
    "made_in_usa": "0",
    "style_number_str": "B89626",
    "promotion_id": "swb1213"
  },
  {
    "brand": "BORN",
    "condition": "New",
    "description": "A versatile slide sandal that sits on a sturdy, comfortable outsole.    Full-grain leather  Leather lining  Rubber with cork outsole  Steel shank  Opanka hand-crafted construction  Heel height: 1 1/2 inches  Sizes: 8M14 Whole Sizes Only",
    "id": 2912,
    "age_group": "Adult",
    "gender": "Men's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/born/Pair/H10303-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=2912&refURL=gcs",
    "price": 95,
    "product_type": "Sandals",
    "title": "Born Men's Shoes - Lionel in Black",
    "color": "Black",
    "gender_str": "Men's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 46,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 538921,
    "made_in_usa": "0",
    "style_number_str": "H10303",
    "promotion_id": "swb1213"
  },
  {
    "brand": "BORN CROWN",
    "condition": "New",
    "description": "A luxurious hand-crafted woven sandal with adjustable straps.   Born Signature Crown Series  Full-grain leather  Leather lining  Rubber outsole  Steel shank  Opanka hand-crafted construction  Heel height: 7/8 inch",
    "id": 2925,
    "age_group": "Adult",
    "gender": "Men's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/Crown/Pair/H09106-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=2925&refURL=gcs",
    "price": 115,
    "product_type": "Sandals",
    "title": "Born Crown Men's Shoes - Shon in Brown",
    "color": "Brown",
    "gender_str": "Men's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 958,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 869044,
    "made_in_usa": "0",
    "style_number_str": "H09106",
    "promotion_id": "swb1213"
  },
  {
    "brand": "SOFTSPOTS",
    "condition": "New",
    "description": "A supple leather slide with relaxed, feminine charm.   Offered in bright patents  Adjustable buckle  Exclusive Pillowtop comfort footbed  Overlasted molded cork unit  Heel Height: 1 inch",
    "id": 6019,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/softspots/Pair/7324711-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6019&refURL=gcs",
    "price": 56.95,
    "product_type": "Sandals",
    "title": "Softspots Women's Shoes - Caileen in Black Crinkle Patent",
    "color": "Black Crinkle Patent",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 285,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 792584,
    "made_in_usa": "0",
    "style_number_str": "7324711",
    "promotion_id": "swb1213"
  },
  {
    "brand": "SOFTSPOTS",
    "condition": "New",
    "description": "A supple leather slide with relaxed, feminine charm.   Offered in bright patents  Adjustable buckle  Exclusive Pillowtop comfort footbed  Overlasted molded cork unit  Heel Height: 1 inch",
    "id": 6020,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/softspots/Pair/7324714-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6020&refURL=gcs",
    "price": 56.95,
    "product_type": "Sandals",
    "title": "Softspots Women's Shoes - Caileen in White",
    "color": "White",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 566,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 214131,
    "made_in_usa": "0",
    "style_number_str": "7324714",
    "promotion_id": "swb1213"
  },
  {
    "brand": "SOFTSPOTS",
    "condition": "New",
    "description": "A supple leather slide with relaxed, feminine charm.   Offered in bright patents  Adjustable buckle  Exclusive Pillowtop comfort footbed  Overlasted molded cork unit  Heel Height: 1 inch",
    "id": 6045,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/softspots/Pair/7324715-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6045&refURL=gcs",
    "price": 56.95,
    "product_type": "Sandals",
    "title": "Softspots Women's Shoes - Caileen in Yellow Crinkle Patent",
    "color": "Yellow Crinkle Patent",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 1975,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 682900,
    "made_in_usa": "0",
    "style_number_str": "7324715",
    "promotion_id": "swb1213"
  },
  {
    "brand": "SOFTSPOTS",
    "condition": "New",
    "description": "A supple leather slide with relaxed, feminine charm.   Offered in bright patents  Adjustable buckle  Exclusive Pillowtop comfort footbed  Overlasted molded cork unit  Heel Height: 1 inch",
    "id": 6046,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/softspots/Pair/7324716-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6046&refURL=gcs",
    "price": 56.95,
    "product_type": "Sandals",
    "title": "Softspots Women's Shoes - Caileen in Turk Green Crinkle Patent",
    "color": "Turk Green Crinkle Patent",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 175,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 762108,
    "made_in_usa": "0",
    "style_number_str": "7324716",
    "promotion_id": "swb1213"
  },
  {
    "brand": "SOFTSPOTS",
    "condition": "New",
    "description": "A supple leather slide with relaxed, feminine charm.   Offered in bright patents  Adjustable buckle  Exclusive Pillowtop comfort footbed  Overlasted molded cork unit  Heel Height: 1 inch",
    "id": 6047,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/softspots/Pair/7324718-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6047&refURL=gcs",
    "price": 56.95,
    "product_type": "Sandals",
    "title": "Softspots Women's Shoes - Caileen in Berry Crinkle Patent",
    "color": "Berry Crinkle Patent",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 952,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 751840,
    "made_in_usa": "0",
    "style_number_str": "7324718",
    "promotion_id": "swb1213"
  },
  {
    "brand": "BORN",
    "condition": "New",
    "description": "Playful buckles and detailed design give this comfort sandal rich character.    Full-grain leather   Leather lining  Polyurethane outsole  Plastic shank  Opanka hand-crafted construction  Heel height: 3 inches",
    "id": 6089,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/born/Pair/B93026-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6089&refURL=gcs",
    "price": 85,
    "product_type": "Sandals",
    "title": "Born Women's Shoes - Timia in Rust",
    "color": "Rust",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 232,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 462879,
    "made_in_usa": "0",
    "style_number_str": "B93026",
    "promotion_id": "swb1213"
  },
  {
    "brand": "SOFTSPOTS",
    "condition": "New",
    "description": "Brushed metallic studs highlight this woven sandal.   Offered in leather  Adjustable buckle  Exclusive Pillowtop comfort footbed  Lightweight outsole  Heel Height: 1 inch",
    "id": 6149,
    "age_group": "Adult",
    "gender": "Women's",
    "availability": "In Stock",
    "google_product_category": "Apparel & Accessories > Shoes",
    "image_link": "http://images.hhbrown.com/softspots/Pair/7329300-130xauto.jpg",
    "link": "http://www.shoeline.com/product.aspx?ProductID=6149&refURL=gcs",
    "price": 59.95,
    "product_type": "Sandals",
    "title": "Softspots Women's Shoes - Hazelle in Light Tan/Tabacco",
    "color": "Light Tan/Tabacco",
    "gender_str": "Women's",
    "style_str": "Sandals",
    "payment_accepted": "Visa,MasterCard,AmericanExpress,Discover",
    "quantity": 305,
    "tax": "::0:",
    "adwords_grouping": "footwear",
    "pageviews": 48874,
    "made_in_usa": "0",
    "style_number_str": "7329300",
    "promotion_id": "swb1213"
  }
			                ];
		} ]);

